// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA35jNpFJ9CCowKcA1jaGZhmj46tPhE2bE',
    appId: '1:759667549541:web:244da461ce3d999c5e6d8c',
    messagingSenderId: '759667549541',
    projectId: 'sportnewsnpl',
    authDomain: 'sportnewsnpl.firebaseapp.com',
    storageBucket: 'sportnewsnpl.appspot.com',
    measurementId: 'G-ZDY4B6NYF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbn5xjV5YUCdz7VjclVV8cQT2XgsCBSCg',
    appId: '1:759667549541:android:d69c9fab07ff58855e6d8c',
    messagingSenderId: '759667549541',
    projectId: 'sportnewsnpl',
    storageBucket: 'sportnewsnpl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADUQrgmAbWJ1gP3130NNZWarmiCbjb6zE',
    appId: '1:759667549541:ios:805f6df6a4d6ef535e6d8c',
    messagingSenderId: '759667549541',
    projectId: 'sportnewsnpl',
    storageBucket: 'sportnewsnpl.appspot.com',
    iosClientId: '759667549541-46241nm0uje07ojaco2u9e6crtnr5ddv.apps.googleusercontent.com',
    iosBundleId: 'com.example.nepalSport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADUQrgmAbWJ1gP3130NNZWarmiCbjb6zE',
    appId: '1:759667549541:ios:99b345c8d20b71025e6d8c',
    messagingSenderId: '759667549541',
    projectId: 'sportnewsnpl',
    storageBucket: 'sportnewsnpl.appspot.com',
    iosClientId: '759667549541-1q6gpmdm3pm4oj6g38j5ucgnjcbuiool.apps.googleusercontent.com',
    iosBundleId: 'com.example.nepalSport.RunnerTests',
  );
}
